language: clojure
lein: lein
dist: xenial
jdk:
  - oraclejdk11
  - openjdk11

addons:
  ssh_known_hosts: shrimp.octet.services

script: lein do clean, test :default :integration

branches:
  only:
    - develop
